version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: siotic-app-prod
    restart: always
    working_dir: /var/www
    env_file: .env
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=siotic
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/var/www
      - ./docker/php.prod.ini:/usr/local/etc/php/conf.d/prod.ini
    networks:
      - siotic-tier-internal

  webserver:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    container_name: siotic-webserver-prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - siotic-tier-public
      - siotic-tier-internal

  db:
    image: mariadb:latest
    container_name: siotic-db-prod
    restart: always
    environment:
      - MARIADB_DATABASE=siotic
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./dbdata_v2:/var/lib/mysql
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/sql/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    command: --innodb-buffer-pool-size=1G --innodb-log-file-size=256M
    networks:
      - siotic-tier-internal

networks:
  siotic-tier-public:
    driver: bridge
  siotic-tier-internal:
    driver: bridge

volumes:
  dbdata_v2:
    driver: local
